apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 11434
        volumeMounts:
          - name: ollama-storage
            mountPath: "{{ .Values.persistence.mountPath }}"
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: "{{ .Values.persistence.existingClaim }}"
