apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.ollama.persistence.pvcName }}"
  namespace: "{{ .Values.ollama.name }}"
  labels:
    app: "{{ .Values.ollama.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.ollama.persistence.size }}"
  storageClassName: "{{ .Values.ollama.persistence.storageClass }}"
