apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.ollama.name }}"
  labels:
    app: "{{ .Values.ollama.name }}"
spec:
  type: {{ .Values.ollama.service.type }}
  selector:
    app: "{{ .Values.ollama.name }}"
  ports:
  - name: http
    port: {{ .Values.ollama.service.port }}
    targetPort: {{ .Values.ollama.service.port }}
    nodePort: {{ .Values.ollama.service.nodePort }}
