apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.ollama.name }}"
  namespace: "{{ .Values.ollama.name }}"
  labels:
    app: "{{ .Values.ollama.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.ollama.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.ollama.name }}"
    spec:
      nodeSelector:
        kubernetes.io/hostname: gravity
      containers:
      - name: "{{ .Values.ollama.name }}"
        image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
        imagePullPolicy: "{{ .Values.ollama.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.ollama.service.port }}
        volumeMounts:
          - name: "{{ .Values.ollama.persistence.storage }}"
            mountPath: "{{ .Values.ollama.persistence.mountPath }}"
      volumes:
        - name: "{{ .Values.ollama.persistence.storage }}"
          persistentVolumeClaim:
            claimName: "{{ .Values.ollama.persistence.pvcName }}"
