apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ollama
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 11434
    nodePort: {{ .Values.service.nodePort }}
