apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
        imagePullPolicy: "{{ .Values.webui.image.pullPolicy }}"
        env:
        - name: OLLAMA_BASE_URL
          value: "{{ .Values.webui.env.OLLAMA_BASE_URL }}"
        ports:
        - containerPort: 8080