apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.webui.name }}"
  labels:
    app: "{{ .Values.webui.name }}"
spec:
  type: {{ .Values.webui.service.type }}
  selector:
    app: "{{ .Values.webui.name }}"
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: {{ .Values.webui.service.port }}
      nodePort: {{ .Values.webui.service.nodePort }}
      protocol: TCP
      name: http
