apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.webui.name }}"
  labels:
    app: "{{ .Values.webui.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.webui.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.webui.name }}"
    spec:
      containers:
      - name: "{{ .Values.webui.name }}"
        image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
        imagePullPolicy: "{{ .Values.webui.image.pullPolicy }}"
        env:
        - name: OLLAMA_BASE_URL
          value: "{{ .Values.webui.env.OLLAMA_BASE_URL }}"
        ports:
        - containerPort: 8080