apiVersion: v1
kind: Service
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  type: {{ .Values.webui.service.type }}
  selector:
    app: open-webui
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.webui.service.nodePort }}
      protocol: TCP
      name: http
