image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 11434         # internal cluster port
  nodePort: 31434     # port on the node (192.168.1.171:31434)

persistence:
  enabled: true
  existingClaim: ollama-pvc
  mountPath: /root/.ollama  # Where Ollama stores models
