
ollama:
  name: ollama
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 11434
    nodePort: 31434
  persistence:
    pvcName: ollama-pvc
    pvName: ollama-pv
    enabled: true
    storageClass: microk8s-hostpath
    size: 500Gi
    mountPath: /root/.ollama

webui:
  name: open-webui
  enabled: true
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: main
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 8080
    nodePort: 30010

  persistence:
    enabled: false
  env:
    OLLAMA_BASE_URL: "http://ollama:11434"
